### PR TITLE
add Dockerfile and .dockerignore files

### PR DESCRIPTION
**Pull request by ahmedkhitaby**
Adding `Dockerfile` and `.dockerignore` for our development environment

### CODE REVIEW

**Comment by elhaw** [comment]
@ahmedkhitaby 
please add a description for what has been done so far.

**Comment by ahmedkhitaby** [comment]
> @ahmedkhitaby please add a description for what has been done so far.

@elhaw  I have added these files for our development environment.
For the production environment, I know the configurations for both Dockerfile and docker-compose but couldn't test it without a `VPS`

**Comment by ahmedkhitaby** [comment]
@elhaw after my meeting with Mr. Ayoub and @ahmedelsayad11 we agreed that there is no need for `VPS` and this is the only docker file we are going to use to deploy our storybook in Heroku after building our project using Github actions.

**Comment by ahmedkhitaby** [comment]
To test this PR

Prerequisite:
- To build our image and run the container you need to have Docker.
[https://docs.docker.com/desktop/](https://docs.docker.com/desktop/)

- Build storybook static files using `yarn build-storybook` command
- You will notice a new `storybook-static` folder that contains our storybook bundle
   - image

- Build our storybook image  `docker build -t m3ntorship_storybook`

- Run our container using `docker run -it -p 3000:3000 m3ntorship_storybook` 
- Now open `http://localhost:3000` in your browser to see our stories

**Comment by elhaw** [comment]
@ahmedkhitaby  
```
docker build -t m3ntorship_storybook 
```
we need to add  `.` at the end of the line so that Docker look for `Dockerfile` in the current directory

**Comment by ahmedkhitaby** [comment]
> @ahmedkhitaby
> 
> ```
> docker build -t m3ntorship_storybook 
> ```
> 
> we need to add `.` at the end of the line so that Docker look for `Dockerfile` in the current directory
> 
> More Info [docs](https://docs.docker.com/get-started/02_our_app/)

okay, I updated the comment. Thanks ❤️

**Pull request merged**
